### ISSUE TITLE
Crash when player joins LAN server.

### ISSUE THREAD

**Issue by maxim0p** [EtherealOnyx/PartiesMod#3]
[full crash log](https://pastebin.com/aGvxWZhE)

The crash happens when a player tries to join a LAN world.

**Comment by EtherealOnyx** [comment]
Thank you for this. The fix has been implemented and I'm fixing a couple more issues before release.

**Comment by EtherealOnyx** [comment]
This has been fixed in version 3.3 [here](https://www.curseforge.com/minecraft/mc-mods/parties/files/4484473)
