### ISSUE TITLE
Parties x Incapacitated

### ISSUE THREAD

**Issue by M1DN1GH7** [EtherealOnyx/PartiesMod#6]
It would be nice if this mod had compatibility with a mod similar to PlayerRevive and HardcoreRevival, [Incapacitated](https://www.curseforge.com/minecraft/mc-mods/incapacitated). It would bring all the needed parity I would need in my modpack

**Comment by EtherealOnyx** [comment]
Wow there's a lot of revival mods 😅
This mod looks great! I'll look into adding support/extra features from it after the next release coming out shortly.

**Comment by EtherealOnyx** [comment]
I apologize for the very long delay, but support has finally been added in version [1.0.0](https://www.curseforge.com/minecraft/mc-mods/parties/files/4708969).

Thanks!
