### ISSUE TITLE
Config file resets every time the game is launched

### ISSUE THREAD

**Issue by mrepicnes** [EtherealOnyx/PartiesMod#7]
The dims config gets reset every time I launch the game, removing all the dimensions I add. Is there a setting in a different config file I need to disable first? I tried making a seperate .json file for the other dims but it doesnt get recognized.

**Comment by EtherealOnyx** [comment]
It should be able to recognize any file inside the dims folder (`config/sedparties/dim`) that ends with `.json` with any file name. The default one is always re-written on load... I apologize that there wasn't much information regarding this.

However, you weren't able to create another file in that folder, like `custom.json` with your custom dim entries in it?

**Comment by mrepicnes** [comment]
I did make another .json file for it; I called it moredims.json and only added one dimension. Its possible I put the wrong dimension in, so let me double check and try again.

I appreciate the swift support!!

**Comment by EtherealOnyx** [comment]
No problem! I'm testing this right now as well.

I noticed that it does indeed not read the other custom dimensions unfortunately. However, you're able to force it to read the dimension entries in game by typing `/party reload`. Do note that this command also re-saves the default presets, reloads all the client configurations, and also loads the default preset in the `sedparties-client.toml`. 

Regardless, it's an issue that will be fixed by the next version. For now, let me know if using that command worked for you!

**Comment by mrepicnes** [comment]
yes! It did work by force-reloading it in game. Looks like its just an issue when the mod is being loaded at first. hopefully its an easy fix!

**Comment by EtherealOnyx** [comment]
I'm sure you will have to keep typing that command every time you reload the game unfortunately. Do let me know. 
A fix will be implemented and released soon, along with a bunch of other things.

**Comment by mrepicnes** [comment]
Well ive accidentally discovered another bug- relogging in another dimension says you're in the overworld; not sure if its just a thing for a dim unspecified in the config or not.

Can confirm that restarting the game reverts to only using the default config file.

**Comment by EtherealOnyx** [comment]
Interesting... What dimension did you load into?

**Comment by mrepicnes** [comment]
in this specific case Ive been testing with the Everdawn from Blue Skies. Works fine when the config is reloaded and recognizing the dimension, but when its unrecognized it just says overworld.

**Comment by EtherealOnyx** [comment]
Oh alright, I only needed to know if it was specified in the config (just saw the edit). That's quite a weird issue because there's no references to the overworld. I will look into this.

As for the issue with custom dim files not being recognized, it's already been fixed on the next version.

**Comment by mrepicnes** [comment]
Awesome! Thanks a lot for the help :))
